llm_provider:
  name: "azure_openai"

  azure_endpoint: "https://my-metis-eu.openai.azure.com/"
  azure_api_version: "2024-02-15-preview"

  engine: "gpt-4o-mini"
  chat_deployment_model: "gpt-4o-mini"

  code_embedding_model: "text-embedding-3-large"
  code_embedding_deployment: "text-embedding-3-large"
  docs_embedding_model: "text-embedding-3-large"
  docs_embedding_deployment: "text-embedding-3-large"

  llama_query_temperature: 0.0
  llama_query_max_tokens: 512

  model_token_param: "max_completion_tokens"
  supports_temperature: false
