name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1

      - name: Create virtual environment
        run: uv venv

      - name: Install test dependencies
        run: uv pip install '.[test]'

      - name: Run tests
        run: uv run pytest

      - name: Run pre-commit checks
        run: |
          uv pip install pre-commit
          uv run pre-commit run --all-files --show-diff-on-failure

      - name: Run Bandit
        run: |
          uv pip install bandit
          uv run bandit -r . -x "./.venv/*","./tests" --severity-level medium
